
version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    command: yarn start:prod
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
